version: '2.4'
services:
  postgres:
    image: postgres:10.5-alpine
    restart: always
    command: postgres -c config_file='/etc/postgresql/postgresql.conf' -c 'hba_file=/etc/postgresql/pg_hba.conf'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf

  # -----------------------------------------------------------------------------------
  # zookeeper
  # -----------------------------------------------------------------------------------
  zookeeper:
    image: bitnami/zookeeper:3.7.0
    platform: linux/x86_64
    hostname: zookeeper
    container_name: zookeeper
    restart: on-failure
    ports:
      - "2181:2181"
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    environment:
      # To allow unauthenticated users to connect to zookeeper - Dev Only Setting
      ALLOW_ANONYMOUS_LOGIN: "yes"

  # -----------------------------------------------------------------------------------
  # Kafka
  # -----------------------------------------------------------------------------------
  kafka:
    image: bitnami/kafka:3.1.0
    hostname: kafka
    container_name: kafka
    restart: on-failure
    ports:
      - "9092:9092"
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ps aux | grep [k]afka || exit -1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      # Since we are using PLAINTEXT for all listeners, need to set this for Bitnami Image
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      # Tell kafka to not authenticate for the custom listeners
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092